CREATE TABLE JEDI.APPLICATION
(
  IDAPPLICATION  NUMBER(3)                      NOT NULL,
  DESCRIPTION    VARCHAR2(100 BYTE)             NOT NULL,
  LASTUSER       VARCHAR2(100 BYTE)             NOT NULL,
  TIMEST         DATE                           NOT NULL
)
TABLESPACE SENATO_DATI
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE TABLE JEDI.FORMATTYPE
(
  IDFORMATTYPE          NUMBER(3)               NOT NULL,
  DESCRIPTION           VARCHAR2(100 BYTE)      NOT NULL,
  MIMETYPE              VARCHAR2(50 BYTE)       NOT NULL,
  TRANSFORMERCLASSNAME  VARCHAR2(200 BYTE)
)
TABLESPACE SENATO_DATI
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE TABLE JEDI.PARAMETERTYPE
(
  IDPARAMETERTYPE  NUMBER(3)                    NOT NULL,
  DESCRIPTION      VARCHAR2(100 BYTE)           NOT NULL,
  CLASSNAME        VARCHAR2(100 BYTE)
)
TABLESPACE SENATO_DATI
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE TABLE JEDI.REUSABLETRANSFORMER
(
  IDREUSABLETRANSFORMER  NUMBER(9)              NOT NULL,
  DESCRIPTION            VARCHAR2(100 BYTE)     NOT NULL,
  TRANSFORMER            CLOB                   NOT NULL,
  LASTUSER               VARCHAR2(100 BYTE)     NOT NULL,
  TIMEST                 DATE                   NOT NULL
)
LOB (TRANSFORMER) STORE AS (
  TABLESPACE  SENATO_DATI
  ENABLE      STORAGE IN ROW
  CHUNK       4096
  PCTVERSION  10
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          20K
                  NEXT             6392K
                  MINEXTENTS       1
                  MAXEXTENTS       249
                  PCTINCREASE      50
                  FREELISTS        1
                  FREELIST GROUPS  1
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE SENATO_DATI
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE TABLE JEDI.XMLSOURCETYPE
(
  IDXMLSOURCETYPE  NUMBER(3)                    NOT NULL,
  DESCRIPTION      VARCHAR2(100 BYTE)           NOT NULL,
  READERCLASSNAME  VARCHAR2(200 BYTE),
  TYPECLASS        NUMBER(2)                    NOT NULL
)
TABLESPACE SENATO_DATI
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN JEDI.XMLSOURCETYPE.TYPECLASS IS '1: Stored procedure 2: JEDI XML Document 3: URL'
/



CREATE UNIQUE INDEX JEDI.APPLICATION_PK ON JEDI.APPLICATION
(IDAPPLICATION)
LOGGING
TABLESPACE SENATO_DATI
NOPARALLEL
/


CREATE UNIQUE INDEX JEDI.FORMATTYPE_PK ON JEDI.FORMATTYPE
(IDFORMATTYPE)
LOGGING
TABLESPACE SENATO_DATI
NOPARALLEL
/


CREATE UNIQUE INDEX JEDI.PARAMETERTYPE_PK ON JEDI.PARAMETERTYPE
(IDPARAMETERTYPE)
LOGGING
TABLESPACE SENATO_DATI
NOPARALLEL
/


CREATE UNIQUE INDEX JEDI.REUSABLETRANSFORMER_PK ON JEDI.REUSABLETRANSFORMER
(IDREUSABLETRANSFORMER)
NOLOGGING
TABLESPACE SENATO_DATI
NOPARALLEL
/


CREATE UNIQUE INDEX JEDI.XMLSOURCETYPE_PK ON JEDI.XMLSOURCETYPE
(IDXMLSOURCETYPE)
LOGGING
TABLESPACE SENATO_DATI
NOPARALLEL
/


CREATE TABLE JEDI.DOCUMENT
(
  IDDOCUMENT             NUMBER(9)              NOT NULL,
  IDAPPLICATION          NUMBER(3)              NOT NULL,
  DESCRIPTION            VARCHAR2(100 BYTE)     NOT NULL,
  IDFORMATTYPE           NUMBER(3)              NOT NULL,
  IDXMLSOURCE            NUMBER(9)              NOT NULL,
  TRANSFORMER            CLOB,
  IDREUSABLETRANSFORMER  NUMBER(9),
  LASTUSER               VARCHAR2(100 BYTE)     NOT NULL,
  TIMEST                 DATE                   NOT NULL
)
LOB (TRANSFORMER) STORE AS (
  TABLESPACE  SENATO_DATI
  ENABLE      STORAGE IN ROW
  CHUNK       4096
  PCTVERSION  10
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          20K
                  NEXT             9588K
                  MINEXTENTS       1
                  MAXEXTENTS       249
                  PCTINCREASE      50
                  FREELISTS        1
                  FREELIST GROUPS  1
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE SENATO_DATI
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE TABLE JEDI.PARAMETER
(
  IDPARAMETER      NUMBER(9)                    NOT NULL,
  IDDOCUMENT       NUMBER(9)                    NOT NULL,
  DESCRIPTION      VARCHAR2(100 BYTE)           NOT NULL,
  IDPARAMETERTYPE  NUMBER(3)                    NOT NULL,
  LASTUSER         VARCHAR2(100 BYTE)           NOT NULL,
  TIMEST           DATE                         NOT NULL
)
TABLESPACE SENATO_DATI
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE TABLE JEDI.XMLSOURCE
(
  IDXMLSOURCE      NUMBER(9)                    NOT NULL,
  IDXMLSOURCETYPE  NUMBER(3)                    NOT NULL,
  IDDOCUMENT       NUMBER(9),
  STOREDPROCEDURE  VARCHAR2(100 BYTE),
  SQLQUERY         VARCHAR2(4000 BYTE),
  URL              VARCHAR2(100 BYTE),
  LASTUSER         VARCHAR2(100 BYTE)           NOT NULL,
  TIMEST           DATE                         NOT NULL
)
TABLESPACE SENATO_DATI
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX JEDI.DOCUMENT_PK ON JEDI.DOCUMENT
(IDDOCUMENT)
NOLOGGING
TABLESPACE SENATO_DATI
NOPARALLEL
/


CREATE UNIQUE INDEX JEDI.PARAMETER_AK ON JEDI.PARAMETER
(IDDOCUMENT, DESCRIPTION)
LOGGING
TABLESPACE SENATO_INDICI
NOPARALLEL
/


CREATE UNIQUE INDEX JEDI.PARAMETER_PK ON JEDI.PARAMETER
(IDPARAMETER)
LOGGING
TABLESPACE SENATO_DATI
NOPARALLEL
/


CREATE UNIQUE INDEX JEDI.XMLSOURCE_PK ON JEDI.XMLSOURCE
(IDXMLSOURCE)
LOGGING
TABLESPACE SENATO_DATI
NOPARALLEL
/


ALTER TABLE JEDI.APPLICATION ADD (
  CONSTRAINT APPLICATION_PK
  PRIMARY KEY
  (IDAPPLICATION)
  USING INDEX JEDI.APPLICATION_PK
  ENABLE VALIDATE)
/


ALTER TABLE JEDI.FORMATTYPE ADD (
  CONSTRAINT FORMATTYPE_PK
  PRIMARY KEY
  (IDFORMATTYPE)
  USING INDEX JEDI.FORMATTYPE_PK
  ENABLE VALIDATE)
/


ALTER TABLE JEDI.PARAMETERTYPE ADD (
  CONSTRAINT PARAMETERTYPE_PK
  PRIMARY KEY
  (IDPARAMETERTYPE)
  USING INDEX JEDI.PARAMETERTYPE_PK
  ENABLE VALIDATE)
/


ALTER TABLE JEDI.REUSABLETRANSFORMER ADD (
  CONSTRAINT REUSABLETRANSFORMER_PK
  PRIMARY KEY
  (IDREUSABLETRANSFORMER)
  USING INDEX JEDI.REUSABLETRANSFORMER_PK
  ENABLE VALIDATE)
/


ALTER TABLE JEDI.XMLSOURCETYPE ADD (
  CONSTRAINT XMLSOURCETYPE_PK
  PRIMARY KEY
  (IDXMLSOURCETYPE)
  USING INDEX JEDI.XMLSOURCETYPE_PK
  ENABLE VALIDATE)
/


ALTER TABLE JEDI.DOCUMENT ADD (
  CONSTRAINT DOCUMENT_PK
  PRIMARY KEY
  (IDDOCUMENT)
  USING INDEX JEDI.DOCUMENT_PK
  ENABLE VALIDATE)
/


ALTER TABLE JEDI.PARAMETER ADD (
  CONSTRAINT PARAMETER_PK
  PRIMARY KEY
  (IDPARAMETER)
  USING INDEX JEDI.PARAMETER_PK
  ENABLE VALIDATE)
/


ALTER TABLE JEDI.XMLSOURCE ADD (
  CONSTRAINT XMLSOURCE_PK
  PRIMARY KEY
  (IDXMLSOURCE)
  USING INDEX JEDI.XMLSOURCE_PK
  ENABLE VALIDATE)
/


ALTER TABLE JEDI.DOCUMENT ADD (
  CONSTRAINT DOC_REFER_APPLICATION 
  FOREIGN KEY (IDAPPLICATION) 
  REFERENCES JEDI.APPLICATION (IDAPPLICATION)
  ENABLE VALIDATE)
/

ALTER TABLE JEDI.DOCUMENT ADD (
  CONSTRAINT DOC_REFER_FORMATTYPE 
  FOREIGN KEY (IDFORMATTYPE) 
  REFERENCES JEDI.FORMATTYPE (IDFORMATTYPE)
  ENABLE VALIDATE)
/

ALTER TABLE JEDI.DOCUMENT ADD (
  CONSTRAINT DOC_REFER_REUS_TRANSF 
  FOREIGN KEY (IDREUSABLETRANSFORMER) 
  REFERENCES JEDI.REUSABLETRANSFORMER (IDREUSABLETRANSFORMER)
  ENABLE VALIDATE)
/

ALTER TABLE JEDI.DOCUMENT ADD (
  CONSTRAINT DOC_REFER_XMLSOURCE 
  FOREIGN KEY (IDXMLSOURCE) 
  REFERENCES JEDI.XMLSOURCE (IDXMLSOURCE)
  ENABLE VALIDATE)
/


ALTER TABLE JEDI.PARAMETER ADD (
  CONSTRAINT PARAMETER_REFER_DOCUMENT 
  FOREIGN KEY (IDDOCUMENT) 
  REFERENCES JEDI.DOCUMENT (IDDOCUMENT)
  ENABLE VALIDATE)
/

ALTER TABLE JEDI.PARAMETER ADD (
  CONSTRAINT PARAMETER_REFER_PARAMTYPE 
  FOREIGN KEY (IDPARAMETERTYPE) 
  REFERENCES JEDI.PARAMETERTYPE (IDPARAMETERTYPE)
  ENABLE VALIDATE)
/


ALTER TABLE JEDI.XMLSOURCE ADD (
  CONSTRAINT XMLSOURCE_REFER_DOC 
  FOREIGN KEY (IDDOCUMENT) 
  REFERENCES JEDI.DOCUMENT (IDDOCUMENT)
  ENABLE VALIDATE)
/

ALTER TABLE JEDI.XMLSOURCE ADD (
  CONSTRAINT XMLSOURCE_REFER_XMLSOURCETYPE 
  FOREIGN KEY (IDXMLSOURCETYPE) 
  REFERENCES JEDI.XMLSOURCETYPE (IDXMLSOURCETYPE)
  ENABLE VALIDATE)
/


--
-- Note: 
-- The following objects may not be sorted properly in the script due to cirular references
--
--  DOCUMENT  (Table) 
--  PARAMETER  (Table) 
--  XMLSOURCE  (Table) 
--  DOCUMENT_PK  (Index) 
--  PARAMETER_AK  (Index) 
--  PARAMETER_PK  (Index) 
--  XMLSOURCE_PK  (Index)
